name: Publish Package to PyPI

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PWD: ${{ secrets.PYPI_MDP }}
  #  TWINE_USERNAME_TEST: ${{ secrets.TESTPYPI_USERNAME }}
  #  TWINE_PWD_TEST: ${{ secrets.TESTPYPI_MDP }}
  # needed environmental variables for running tests
  HOST: ${{ secrets.HOST }}
  PARADIGM_API_KEY: ${{ secrets.PARADIGM_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Test package
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install dist/*.whl
          python3 -m pytest

      #      - name: Publish to TestPyPI
      #        uses: pypa/gh-action-pypi-publish@release/v1
      #        with:
      #          user: ${{ env.TWINE_USERNAME_TEST }}
      #          password: ${{ env.TWINE_PWD_TEST }}
      #          repository-url: https://test.pypi.org/legacy/
      #          packages-dir: ./dist/
      #          skip_existing: true

      - name: Publish to PyPI
        # add conditions to only deploy when a tag started with 'v'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ env.TWINE_USERNAME }}
          password: ${{ env.TWINE_PWD }}
          #repository-url: https://upload.pypi.org/legacy/
          packages-dir: ./dist/